name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci  # Clean install using package-lock.json

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/gh-pages@v3
        with:
          build_dir: dist  # Folder containing the built artifacts
          github_token: ${{ secrets.GITHUB_TOKEN }}
